# Generated by Django 6.0.4 on 2026-04-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='leagues.league')),
            ],
            options={
                'ordering': ['league', 'number'],
                'unique_together': {('league', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_legs', models.PositiveIntegerField(default=0)),
                ('player2_legs', models.PositiveIntegerField(default=0)),
                ('highscore', models.PositiveIntegerField(blank=True, null=True)),
                ('highfinish', models.PositiveIntegerField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1', to='players.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player2', to='players.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='players.player')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.matchday')),
            ],
            options={
                'ordering': ['matchday', 'id'],
            },
        ),
    ]
