# Generated by Django 6.0.4 on 2026-04-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='highscore',
        ),
        migrations.CreateModel(
            name='MatchHighscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_highscores', to='players.player')),
            ],
            options={
                'ordering': ['-value', 'id'],
            },
        ),
    ]
