# Generated by Django 6.0.4 on 2026-04-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_match_highscore_matchhighscore'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='highfinish',
        ),
        migrations.CreateModel(
            name='MatchSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_type', models.CharField(choices=[('180', '180'), ('highfinish', 'Highfinish')], max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_specials', to='players.player')),
            ],
            options={
                'ordering': ['match', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='MatchHighscore',
        ),
    ]
