# Generated by Django 6.0.4 on 2026-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_highfinish_matchspecial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['matchday', 'id'], 'verbose_name': 'Spiel', 'verbose_name_plural': 'Spiele'},
        ),
    ]
