# Generated by Django 6.0.4 on 2026-05-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_autodarts_stats'),
        ('matches', '0005_matchplayerstat'),
    ]

    operations = [
    ]
