# Generated by Django 6.0.4 on 2026-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_merge_0005_match_autodarts_stats_0005_matchplayerstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1_avg_first9',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_avg_to_170',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_avg_total',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_checkout_percent',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_avg_first9',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_avg_to_170',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_avg_total',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_checkout_percent',
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='throws_100_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='100+'),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='throws_140_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='140+'),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='throws_170_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='170+'),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='throws_180',
            field=models.IntegerField(blank=True, null=True, verbose_name='180'),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='throws_60_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='60+'),
        ),
    ]
