# Generated by Django 6.0.4 on 2026-04-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_players', models.PositiveIntegerField(default=12)),
                ('is_public', models.BooleanField(default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leagues', to='leagues.leaguetier')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='leagues.season')),
            ],
            options={
                'ordering': ['tier__order', 'name'],
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaguePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_players', to='leagues.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_entries', to='players.player')),
            ],
            options={
                'ordering': ['league', 'player'],
                'unique_together': {('league', 'player')},
            },
        ),
    ]
