# Generated by Django 6.0.4 on 2026-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagueplayer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leagueplayer',
            constraint=models.UniqueConstraint(fields=('player',), name='unique_player_one_league'),
        ),
    ]
