# Generated by Django 6.0.4 on 2026-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Spieler gesperrt'),
        ),
    ]
