# Generated by Django 6.0.4 on 2026-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_player_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['display_name'], 'verbose_name': 'Spieler', 'verbose_name_plural': 'Spieler'},
        ),
        migrations.AlterField(
            model_name='player',
            name='autodarts_name',
            field=models.CharField(max_length=100, verbose_name='Autodarts Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(max_length=100, verbose_name='Discord Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Spieler aktiv'),
        ),
    ]
