# Generated by Django 6.0.4 on 2026-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_options_alter_player_autodarts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='autodarts_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Autodarts Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Discord Name'),
        ),
    ]
